blueprint:
  name: Aqara TRV E1 external temperature
  description: >
    Configures the Aqara TRV to receive it's temperature from an external sensor.
    Every time the temperature & door sensor value changes it's is send to the TRV.
  domain: automation
  source_url: "https://github.com/jmorille/home-assistant-blueprint/z2m_aqara_trv_external_temperature.yaml"
  input:
    external_temp_sensor:
      name: External temperature sensor
      description: This temperature sensor values will be synced to the TRV
      selector:
        entity:
          multiple: false
          filter:
            domain: sensor
            device_class:
              - temperature
    external_contact_sensor:
      name: External contact sensor
      description: This contact sensor values will be synced to the TRV
      selector:
        entity:
          multiple: true
          filter:
            domain: binary_sensor
            device_class:
              - door
    aqara_trv_device:
      name: The Aqara TRV
      description: The TRV that the temperature willl be set to
      selector:
        device:
          multiple: false
          filter:
            - integration: mqtt
              manufacturer: Xiaomi
              model: Aqara Smart Radiator Thermostat E1 (SRTS-A01)

mode: restart
max_exceeded: silent

variables:
  aqara_trv_device: !input aqara_trv_device
  external_temp_sensor: !input external_temp_sensor
  external_contact_sensor: !input external_contact_sensor

trigger:
  - platform: state
    entity_id: !input external_temp_sensor
  - platform: state
    entity_id: !input external_contact_sensor
    to: "on"
    id: window-open
  - platform: state
    entity_id: !input external_contact_sensor
    to: "off"
    id: window-close
action:
  - variables:
      aqara_trv_device_name: "{{ device_attr(aqara_trv_device, 'name') }}"
      aqara_trv_select_entity: >-
        {% set device_entities = device_entities(aqara_trv_device) %}
        {{ expand(device_entities)
                  | selectattr('attributes.options', 'contains', 'external')
                  | map(attribute='entity_id') 
                  | first
        }}
      aqara_trv_climate_entity: >-
        {% set device_entities = device_entities(aqara_trv_device) %}
        {{ expand(device_entities)
                  | selectattr('attributes.hvac_modes', 'contains', 'off')
                  | map(attribute='entity_id') 
                  | first
        }}
  - if:
      - condition: template
        value_template: "{{ not is_state(aqara_trv_select_entity, 'external')}}"
    then:
      - service: select.select_option
        target:
          entity_id: "{{aqara_trv_select_entity}}"
        data:
          option: external
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
  - service: mqtt.publish
    data:
      topic: "zigbee2mqtt/{{aqara_trv_device_name}}/set/sensor_temp"
      payload_template: >-
        {{ (states(external_temp_sensor)|float(0)) }}
  - choose:
      - conditions:
          - condition: trigger
            id:
              - window-open
        sequence:
          - service: climate.turn_off
            target:
              entity_id: "{{aqara_trv_climate_entity}}"
            data: {}
      - conditions:
          - condition: trigger
            id:
              - window-close
        sequence:
          - service: climate.turn_on
            target:
              entity_id: "{{aqara_trv_climate_entity}}"
            data: {}
