blueprint:
  name: Aqara TRV E1 external temperature
  description: >
    Manage the Aqara TRV from external temperature sensor event or door contact event.
  domain: automation
  source_url: "https://github.com/jmorille/home-assistant-blueprint/z2m_aqara_trv_external_temperature.yaml"
  input:
    external_temp_sensor:
      name: External temperature sensor
      description: This temperature sensors from min values
      selector:
        entity:
          multiple: true
          filter:
            domain: sensor
            device_class:
              - temperature
    external_temp_comparator:
      name: Temperature comparator from sensors
      description: This temperature comparator from sensors values
      selector:
        select:
          options:
            - min
            - max
            - avg
            - first
            - last
      default: avg

    external_contact_sensor:
      name: External contact sensor
      description: Doors Contact sensor values will shut off the TRV
      selector:
        entity:
          multiple: true
          filter:
            domain: binary_sensor
            device_class:
              - door
        
    aqara_trv_shutoff:
      name: Aqara TRV shutoff methods
      description: The shutoff when contact is open
      selector:
        select:
          options:
            - away
            - close
      default: away

    aqara_trv_device:
      name: The Aqara TRV
      description: The TRV that the temperature willl be set to
      selector:
        device:
          multiple: true
          filter:
            - integration: mqtt
              manufacturer: Xiaomi
              model: Aqara Smart Radiator Thermostat E1 (SRTS-A01)
mode: restart
max_exceeded: silent

variables:
  aqara_trv_device: !input aqara_trv_device
  external_temp_sensor: !input external_temp_sensor
  external_temp_comparator: !input external_temp_comparator
  external_contact_sensor: !input external_contact_sensor
  aqara_trv_shutoff: !input aqara_trv_shutoff
  
trigger:
  - platform: state
    entity_id: !input external_temp_sensor
    id: temp-change
  - platform: state
    entity_id: !input external_contact_sensor
    to: "on"
    id: window-open
  - platform: state
    entity_id: !input external_contact_sensor
    to: "off"
    id: window-close
action:
  - variables:
#      aqara_trv_device_name: "{{ aqara_trv_device | map('device_attr', 'name') | list }}"
      aqara_trv_select_entity: >-   
        {{ aqara_trv_device | map('device_entities') | sum(start=[]) | expand
        | selectattr('attributes.options', 'contains', 'external')
        | map(attribute='entity_id') | list
        }}
      aqara_trv_climate_entity: >-
        {{ aqara_trv_device | map('device_entities') | sum(start=[]) | expand
        | selectattr('attributes.hvac_modes', 'contains', 'off')
        | map(attribute='entity_id') | list 
        }}
      aqara_trv_sensor_temp_entity: >-
        {% set ns = namespace(sensor_temp=[])%} 
        {% for elt in aqara_trv_climate_entity %}
           {% set ns.sensor_temp = ns.sensor_temp + [elt+'_sensor_temp']%}  
        {% endfor -%}
        {{ ns.sensor_temp | replace('climate', 'number')  }}
      aqara_compute_temperature: >-
        {% set external_temp_list = expand(external_temp_sensor)  | map(attribute='state') | map('float')  | list -%}
        {% if external_temp_comparator == 'min' -%}
          {{ external_temp_list | min   }}
        {%- elif external_temp_comparator == 'max' -%}
          {{external_temp_list | max   }}
        {%- elif external_temp_comparator == 'first' -%}
          {{external_temp_list | first   }}          
        {%- elif external_temp_comparator == 'last' -%}
          {{external_temp_list | last   }}          
        {%- else -%}
          {{ ((external_temp_list | sum) / (external_temp_list | count)) | round(3) }}
        {%- endif %} 

  - parallel:
      - if:
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ True }}"            
              - condition: trigger
                id:
                  - temp-change

        then:
          # ### Check TRV config from external temperature sensor ### #
          # ### ################################################# ### #      
          - variables:
              # Get all in internal states for change it   
              aqara_trv_select_entity_internal: "{{ aqara_trv_select_entity | expand | selectattr('state', 'eq', 'internal')  | map(attribute='entity_id')  | list }}"

          - if:
              - condition: template
                value_template: "{{ aqara_trv_select_entity_internal | count > 0 }}"
            then:
              - service: select.select_option
                target:
                  entity_id: "{{ aqara_trv_select_entity_internal }}"
                data:
                  option: external
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 1
                  milliseconds: 0 
                  
          # ### Publish external temperature ### #
          # ### ############################ ### #      
          # Repeat for all names
          - service: number.set_value
              target:
              entity_id:
                target:
                  entity_id: "{{aqara_trv_sensor_temp_entity}}"
      - choose:
          # ### Test Radiator for Turn OFF ### #
          # ### ########################## ### #      
          - conditions:
              - condition: trigger
                id:
                  - window-open
            sequence:
              - service: climate.turn_off
                target:
                  entity_id: "{{aqara_trv_climate_entity}}"
                data: {}
              # Radiator Turn OFF
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ aqara_trv_shutoff == 'close' }}"
                    sequence:
                      # Radiator OFF: by Turn Off Service
                      - service: climate.turn_off
                        target:
                          entity_id: "{{aqara_trv_climate_entity}}"
                        data: {}
                  - conditions:
                      - condition: template
                        value_template: "{{ aqara_trv_shutoff == 'away' }}"
                    sequence:
                      # Radiator OFF: by Preset Away Mode config temp consigne 
                      - service: climate.set_preset_mode
                        target:
                          entity_id: "{{aqara_trv_climate_entity}}"
                        data:
                          preset_mode: away

          # ### Test Radiator for Turn ON  ### #
          # ### ########################## ### #
          - conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id:
                      - window-close
                  - condition: template
                    value_template: >-
                      {{ expand(external_contact_sensor) |  selectattr('state', 'eq', 'on')  | list | count == 0 }}
            sequence:
              # Radiator check Turn ON Method
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ aqara_trv_shutoff == 'close' }}"
                    sequence:
                      # Radiator ON: by Turn On Service
                      - service: climate.turn_on
                        target:
                          entity_id: "{{aqara_trv_climate_entity}}"
                        data: {}
                  - conditions:
                      - condition: template
                        value_template: "{{ aqara_trv_shutoff == 'away' }}"
                    sequence:
                      # Radiator ON: by Preset Auto Mode config temp consigne 
                      - service: climate.set_preset_mode
                        target:
                          entity_id: "{{aqara_trv_climate_entity}}"
                        data:
                          preset_mode: auto
